### ISSUE TITLE
Support users upload via CSV (CSV validation) (BE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#102]
[Wiki - adding user flow](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#1-adding-users)
[CSV table fields and rules](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#af-1a)

[Validation view ](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=442%3A47210&t=wdgWfe0YR9iCAwi3-1)

Relates to:
- Tags

**To-do:**
- Backend file (format, headers, fields) validation request 
- saving file when validated in FE
- create endpoint for getting user list with associated users data
- validate user permissions: "Kasutajate lisamine süsteemi" (add_user) 
- user creation is logged to audit logs

**Comment by kadmit** [comment]
Regarding departments:

Based on the requirements department is not a mandatory field 🙂 

> 1.4 User uploads CSV with the following columns:
> ...
> Üksus (Department) of the Institution (Harju Maakohus) - not mandatory field, but department is added system must check it exists in the Institutions department list.


https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#1-adding-users

**Comment by MariusJulius** [comment]
Yes, solved now. There was wiki older version linked. Fixed that. Vendor not there, department not mandatory.
