### ISSUE TITLE
User management view (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#104]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)/e7e358c7626b0eb80d131b9818fe55f29c7dcc45#1-adding-users)
[Design - empty](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=439%3A44223&t=JVjjCtZuZIxCTcIj-1)
[Design - not empty](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?type=design&node-id=646%3A55089&mode=design&t=jICpFte0wDxML6Zy-1)

Prerequisite:

[Table features#133](https://github.com/keeleinstituut/tv-tolkevarav/issues/133)

To-do:
* create user management section views
   * intially only "main user" (added with script) and the possibility to add users; 
   * display users list like in the design
      *  filtering by status
      *  sorting by columns (üksus, roll, staatus) (department, role, status)

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

It's OK
