### ISSUE TITLE
Institution selection FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#106]
[Institution selection](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=936%3A91615&t=u2dAjFE4UBz4V5E6-1)

Prerequisite:
Modal component task #259 

**To-do:**
- Institution selection view on login (when more than 1 institutions related to user)

**Comment by KaarelKa** [comment]
@MariusJulius Hey can we split this task into 2 ? Dashboard view task should be blocked behind Header and Sidebar component tasks and Institution selection task should be blocked behind Modal component task

**Comment by MariusJulius** [comment]
Separated dashboard here: https://github.com/keeleinstituut/tv-tolkevarav/issues/258

**Comment by plakitkelly** [comment]
Tested with Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)
(Also checked with Edge and Firefox)

It's OK
