### ISSUE TITLE
Adding users table and CSV validation views (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#117]
[User flow](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)/#1-adding-users)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=170%3A10686&t=w2GgKmoZKfnZNfCw-0)

Related BE task #102 
Table component: #133

To-do:
- adding csv view
- csv uploaded view
- table validation view
- table saved view (users management main view) #104
- allowing to view and add users for user with privileges: "Kasutajate vaatamine" (view_user) and "Kasutajate lisamine süsteemi" (add_user)

**Comment by KaarelKa** [comment]
Had quick discussion with @thenouan 

Initially the flow for FE will be :

1. User uploads CSV
2. FE does request to POST /institution-users/validate-import-csv endpoint with the csv
3. BE sends any validation errors that might exist
4. FE displays all users in a table
5. FE shows all error messages we got from BE + makes the corresponding fields editable
6. User fixes all the errors (Note* also use FE validation in this step)
7. User presses the submit button
8. FE generates new csv with the fixes and does request to POST /institution-users/validate-import-csv 
9. If BE returns errors, then go to 5.
10. If there are no errors, then show success alert and navigate the user to "Kasutajate haldus" view

**Comment by KaarelKa** [comment]
@MariusJulius This task has been done partially. Things left to do.

1. Add correct table component (currently we have a placeholder there)
2. Add breadcrumbs (Should be a separate task, we need it in other places as well)
3. User management view (Will be done in task 104)
4. Privilege handling - The case here will be handled with global privilege handling, which isn't done yet (Users without the add_user or view_user privilege will not get to this page at all)

**Comment by plakitkelly** [comment]
Preconditions: User has activate_user privilege but doesn't have view_role privilege.
Another user has deactivated

Steps:
1. Click on "Aktiveeri" button
2. Choose roles

Actual:
User cannot choose the role

Expected:
view_role should be for "Rollihaldus" table, not activating the user

**Comment by plakitkelly** [comment]
[users - Copy.csv](https://github.com/keeleinstituut/tv-tolkevarav/files/12214886/users.-.Copy.csv)
CSV file for testing. (2 users in file, 1st is deactivated, 2nd is new user)

**Comment by plakitkelly** [comment]
[users - Copy.csv](https://github.com/keeleinstituut/tv-tolkevarav/files/12214977/users.-.Copy.csv)
In this file I have 3 new users. 1st has same PIC what is deactivated. 2nd has same PIC what is archived. 3rd is new user. 

I can't add 2nd user, because this PIC is already in system.

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

It's OK

Adding archived PIC is there #410
