### ISSUE TITLE
Role creation in role management (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#119]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)#21-creating-a-new-role)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=466-69517&t=2tud0LZHfLwqhABO-0)

BE task #118 
Modal task #263 

To-do:
- creating views in role management view (rollihaldus) for adding new role and privileges
- showing added role and privileges
- validating user permissions - "Rollihalduse tabeli vaatamine" (view_roles), "Rolli lisamine süsteemi" (add_role) for viewing and editing roles

AC:
- user can add new role "lisa uus roll"
- user can select privileges
- user can save role and privileges
- user can cancel creation
- user with only view_roles privilege can't create, delete, edit roles and privileges

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

It's OK
