### ISSUE TITLE
Editing and view changed roles / privileges (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#120]
[Flow](https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)#22-editing-a-role)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=427%3A46783&t=w2GgKmoZKfnZNfCw-0)

To-do:
- enable editing existing role and privileges
- enable saving role and privileges changes
- making sure user has the right privileges -  "Rollihalduse tabeli vaatamine" (view_roles), "Rolli muutmine (privileegide lisamine/ eemaldamine)" (edit_role)

**Comment by MariusJulius** [comment]
@KaarelKa  change in the logic - [Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)#22-editing-a-role) AF.2.2a if role is initial main user.

**Comment by plakitkelly** [comment]
Tested with Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)

It's OK
