### ISSUE TITLE
Viewing role table (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#123]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)#24-viewing-the-roles-table)

Prerequisite:
User has only view_roles privilege

To-do:
- Limit user with view_roles privilege from any action related to role or privileges changes

**Comment by plakitkelly** [comment]
preconditions:
User has only view_roles privilege

Steps: 
1. Open Rollihaldus
2. Choose any role
3. Click on edit button in role name tab
4. Edit role name

Actual: 
Everything seems correct, this user cannot change role name or privileges, but can edit role name. (can't save)

@MariusJulius I couldn't find in the documentation how it should be, but it would be more logical that the user with view_role privilege could not edit role name. What do you think should the edit button be removed or should it be as it is? 


https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/e90bca01-7bc0-4c96-a7a8-aa875cf79036

**Comment by MariusJulius** [comment]
1) Okay, so in the UI it let's user to edit but doesn't save actually. So editing name needs to be disabled if only view privileges.
2) Another thing I noticed - up for discussion that if I have adding and editing but not viewing then should I access the view if not it should not show the menu item or inform that privilege is missing @PlaksoBirgit

**Comment by plakitkelly** [comment]
2. There is discussion about this https://pundar.slack.com/archives/C053FD55ATT/p1689235055506779

**Comment by plakitkelly** [comment]
Created new issue for editing role name #423

**Comment by plakitkelly** [comment]
Other limits works well with view_roles, OK
