### ISSUE TITLE
Make tags editable in tags management view (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#125]
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=936%3A92408&t=0eH5ypeJoJPadoYd-1)

BE task #126 

To-do:
- create tag category update modal
- enable adding and editing of tags in the modal
- only user with privilege "Siltide muutmine" (edit_tag) can edit tagas

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.171 (Official Build) (64-bit))

It's OK
