### ISSUE TITLE
Deleting tag functionality (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#127]
[Wiki](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=936%3A92408&t=0eH5ypeJoJPadoYd-1)
[Design (modal)](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=936-92408&t=FKnRjj8vmJJLl2zh-0)

BE task #128 

To-do:
- enable removing tags through tag category modal
- showing update list of tags
- user with privilege "Siltide kustutamine" (delete_tag) can delete tags

**Comment by IngaSokman** [comment]
Task is done under task: https://github.com/keeleinstituut/tv-tolkevarav/issues/125

**Comment by plakitkelly** [comment]
User with only delete_tag privilege cannot delete tag, because user cannot click on "Salvesta" button without edit_tag privilege.

**Comment by plakitkelly** [comment]
Created new issue #446 

Deleting actually works, I mark it as Done
