### ISSUE TITLE
Removing role (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#136]
[Wiki - initial](https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)#23-deleting-a-role)
[Wiki - changes compared](https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)/_compare/43cdabf1193716758b5b50f126e6355511b97c13...f0e19bb4ea6c470c239d0323dd3e7274b7f78324)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=466%3A69517&t=2tud0LZHfLwqhABO-1)

Endpoint validation BE: https://github.com/keeleinstituut/tv-tolkevarav/issues/281

To-do
- [ ] enable removing role from the UI
- [ ] Showing popup if it is not possible to remove a role (attached to some users)
- [ ] Showing updated role and privilege view
- [ ] validating if user has the right privileges for deleting - "Rollihalduse tabeli vaatamine" (view_roles), "Rolli kustutamine" (delete_role).

**Comment by KaarelKa** [comment]
@thenouan "Showing popup if it is not possible to remove a role (attached to some users)" - Will we get this as an error from BE, when attempting to delete ?

**Comment by KaarelKa** [comment]
@thenouan Actually according to https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)#23-deleting-a-role I need to show this message before I use the delete endpoint, so this information should be included with the roles and/or should be available from some separate endpoint.

**Comment by KaarelKa** [comment]
Blocked for now, couldn't find endpoint for validating if role can be deleted or not

**Comment by MariusJulius** [comment]
Issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/281

**Comment by MariusJulius** [comment]
Created new issue and linked it.

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

It's OK
