### ISSUE TITLE
User data editing (BE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#137]
[User flow](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#2-editing-user-data)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=442%3A47981&t=6shLi0sBIw1IJ7HR-1)

To-do
- update data model in authorization service (a.k.a organization service) to include departments and user’s phone number
- create an endpoint for updating user object data
- create endpoint for getting single user data
- checking user permissions - "Kasutajate andmete muutmine" (edit_user)

NB! 
* Doesn't include calendar part which will be done separately in #191. 
* Editing whether the user is a vendor or not will be handled by a separate endpoint in the translation order service.

**Comment by MariusJulius** [comment]
@DanBondarenko there were some changes in the flow - Wiki p.2.4 So the main user role couldn't be removed from the user if it is assigned to only 1 user.

**Comment by DanBondarenko** [comment]
> @DanBondarenko there were some changes in the flow - Wiki p.2.4 So the main user role couldn't be removed from the user if it is assigned to only 1 user.

OK. Moving the issue back to TODO status. Should this be priority no. 1 or should I tackle this after my current tasks (#179, #181, #210)?

Also, there are some issues with the new requirements, I raised the questions i have [in Slack](https://pundar.slack.com/archives/C048W5ZV1ST/p1685101604521179).

**Comment by MariusJulius** [comment]
Yes, lets solve the questions first and then take the tasks.

**Comment by MariusJulius** [comment]
Moving this back to ready for testing and adding changes to separate issues.
