### ISSUE TITLE
User data editing (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#138]
[User flow](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#2-editing-user-data)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=442%3A47981&t=6shLi0sBIw1IJ7HR-1)

Related BE task: #137 

- Doesn't include working/vacations times part which will be done separately in #191 
- Deactivation/activation flow and functionality described in other issues

To-do
- [ ] create user data management view
- [ ] enable editing user data fields (edit, cancel, confirm)
- [ ] validating user permissions to be able to edit data - "Kasutajate andmete muutmine" (edit_user)

**Comment by MariusJulius** [comment]
Yes, will to it later today or tomorrow morning

**Comment by MariusJulius** [comment]
@KaarelKa there were some changes in the flow - Wiki p.2.4 So the main user role couldn't be removed from the user if it is assigned to only 1 user.

**Comment by plakitkelly** [comment]
Tested with Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)
(Also checked with Edge and Firefox)

It's OK
