### ISSUE TITLE
Deactivating user (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#140]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#3-deactivating-the-account)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=442%3A47981&t=6shLi0sBIw1IJ7HR-1)

Prerequisite:
Backend task #295 
[Modal component#259](https://github.com/keeleinstituut/tv-tolkevarav/issues/259)

To-do:
- [ ] deactivation from user management view
- [ ] deactivation confirmation modal with date selection
- [ ] showing deactivation date under user view
- [ ] validating user permissions to perfom actions - "Kasutajate deaktiveerimine" (deactivate_user)

**Comment by IngaSokman** [comment]
@MariusJulius In the design I do not see edit button next to date of the future deactivation, but in Wiki it is described. Is it possible to edit the deactivation date? What should the icon be (I assume the same as in at the end of rows "Tööajad" and "Puhkepäevad" pencil icon)?

**Comment by MariusJulius** [comment]
@IngaSokman seems so, missed it myself. Added a comment to figma as well - fyi for @PlaksoBirgit @martinepai.

**Comment by IngaSokman** [comment]
@KaarelKa Noticed that when model is opened the first input element is being focused. So when my first input element is calendar, then when modal is opened then calender is automatically opened as well. Is this behaviour meant that way?

**Comment by KaarelKa** [comment]
@IngaSokman Let's get rid of the auto focus when modal opens. I don't think it should behave like that

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

It's OK
