### ISSUE TITLE
Activating user account (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#146]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#4-activating-the-account)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=442%3A47981&t=6shLi0sBIw1IJ7HR-1)

Related backend task: #145 

To-do
- [ ] views for reactivating users and flow (activation modal view, role selection)
- [ ] Validating if user has the privilege "Kasutajate aktiveerimine" (activate_user)

**Comment by plakitkelly** [comment]
Preconditions: User has activate_user privilege but doesn't have view_role privilege.
Another user has deactivated

Steps:

Click on "Aktiveeri" button
Choose roles
Actual:
User cannot choose the role

Expected:
view_role should be for "Rollihaldus" table, not activating the user
![image](https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/c972ffbe-bf83-4fba-8102-f4f2ef52ab61)

**Comment by plakitkelly** [comment]
Created new issue #424

**Comment by plakitkelly** [comment]
views for reactivating users and flow (activation modal view, role selection)
 Validating if user has the privilege "Kasutajate aktiveerimine" (activate_user)

are OK
