### ISSUE TITLE
Arhiving user account (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#148]
[Design - flow start](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=442%3A47981&t=KkjjblDEAy9GQBxo-1)
[Design - archive modal](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=1732%3A89660&t=KkjjblDEAy9GQBxo-1)

BE task: #293 

To-do:
- implement user archiving flow and views
- validate user permissions for actions - User has the privilege  "Kasutajate arhiveerimine" (archive_user)

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

It's OK
