### ISSUE TITLE
Export CSV (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#150]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#6-exporting-users)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?type=design&node-id=427%3A38206&mode=design&t=2jCpjzKxbp2ptnIy-1)

BE: #149 

To-do:
- adding button and download functionality for CSV
- validating user permissions for exporting - "Kasutajate nimekirja eksport" (export_user)

**Comment by KaarelKa** [comment]
@VaabelMaret Seems this csv will not be generated by FE. There was a BE ticket for this, so we should have a BE endpoint ready for generating the csv https://github.com/keeleinstituut/tv-tolkevarav/issues/149

**Comment by plakitkelly** [comment]
@MariusJulius Which character encoding is used when creating the output file? I think "õäöü" should be in csv. Use utf-8 encoding.


![Image](https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/104f9f91-5e45-47d7-8c2f-3419a010cf0b)

**Comment by MariusJulius** [comment]
@kadmit will check in separate issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/409

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

Exporting is OK, I move this issue to Done. 
We continue with #409
