### ISSUE TITLE
Edit single vendor in vendors database (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#155]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/6.-Asutuse-peakasutaja-vaade#28-flow-editing-vendors-database) (update link after design change)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=757%3A93909&t=mgHRRWa7fNK7d4Ct-1)

Related issue:
- #209 
- BE #154 

To-do:
- creating single user view and enabling editing vendor data and price percentages
- checking user privilege User has the privilege "Teostajate andmebaasi muutmine" (edit_vendor_db)

**Comment by MariusJulius** [comment]
@plakitkelly I noticed already that "Tühista" buttons cancels the changes that are saved, but I'm waiting other feedback as well before creating new issue.

**Comment by MariusJulius** [comment]
https://github.com/keeleinstituut/tv-tolkevarav/issues/460

**Comment by plakitkelly** [comment]
Seems that "Tühista" button doesn't cancel saved data anymore. 

Tested in 06.10 with Google Chrome Versioon 117.0.5938.150 (Ametlik järk) (64-bitine)

It's OK
