### ISSUE TITLE
Adding vendors management related privileges to authorisation service (BE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#189]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/6.-Asutuse-peakasutaja-vaade#25-the-list-of-translation-agencies-and-in-house-translators-can-be-addedchangedsupplementedcancelled-by-the-institution-administrator-and-the-system-administrator)

To-do:
Adding privileges to authorisation service:
- "Teostajate andmebaasi vaatamine" (view_vendor_db)
- "Teostajate andmebaasi muutmine" (edit_vendor_db) 
- "Teostajate koondhinnakirja vaatamine" (view_general_pricelist)
- "Teostaja ülesannete vaatmine"  (view_vendor_task)

**Comment by DanBondarenko** [comment]
@MariusJulius This issue mentions three privileges, but the Wiki talks about more than three vendor-related privileges. Should I just add the three or all vendor-related ones?

Mentioned in [Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/6.-Asutuse-peakasutaja-vaade) and [privilege table](https://pundar.atlassian.net/wiki/spaces/TLKEV/pages/2076737562/Rollide+privileegide+tabel), but missing from this GitHub issue:
* `view_institution_price_rate`
* `view_general_pricelist`
* `view_vendor_task`

**Comment by MariusJulius** [comment]
@DanBondarenko 

I removed “edit_institution_price_rate”  and added view_general_pricelist and view_vendor_task - those are related to vendors section

view_institution_price_rate I could not see - maybe this was changed, by the name it seems to relate to other view (as the edit_institution_price_rate)
