### ISSUE TITLE
Creating new translation memory (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#222]
[Wiki - creation flow](https://github.com/keeleinstituut/tv-tolkevarav/wiki/7.-T%C3%B5lkem%C3%A4lude-haldusmoodul-(T%C3%B5lkem%C3%A4lude-genereerimine-ja-t%C3%B5lkem%C3%A4lude-allalaadimise-v%C3%B5imalus)#31-flow-creating-translation-memory)
[Wiki - Translation Memory object data](https://github.com/keeleinstituut/tv-tolkevarav/wiki/7.-T%C3%B5lkem%C3%A4lude-haldusmoodul-(T%C3%B5lkem%C3%A4lude-genereerimine-ja-t%C3%B5lkem%C3%A4lude-allalaadimise-v%C3%B5imalus)#2-translation-memory-objects-data-fields)
[Figma design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=708-118324&t=fjs7Ddh35m6q1k4Y-4)

BE task #183 
FE - should be done together with #224 (Part of the same flow)

To-do:
 - endpoint(s) for creating new translation memory
 - checking user permissions against "Asutuse tühja tõlkemälu loomine" (create_tm) privilege

**Comment by plakitkelly** [comment]
Testen in 12.10 - It's OK
