### ISSUE TITLE
User dashboard view (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#258]
[Dashboard](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=640%3A84364&t=u2dAjFE4UBz4V5E6-1)

Prerequisite
- Header and Sidebar component tasks (https://github.com/keeleinstituut/tv-tolkevarav/issues/132)

To-do:
- user dashboard view

**Comment by plakitkelly** [comment]
Tested with Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)
(Also checked with Edge and Firefox)

It's OK
