### ISSUE TITLE
Validation if role can be deleted (BE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#281]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)#23-deleting-a-role)

An additional issue related to #136 for validating if role can be deleted to be used in the popup modal

To-do:
- Validating if role can be deleted (is_root=true and it's not the only user with that role)

**Comment by thenouan** [comment]
There's no need for extra endpoint for this. FE can validate based on the is_root field and BE can do the same when request is made to role update endpoint or role deletion endpoint, both endpoints should deny the request
