### ISSUE TITLE
Editing roles - is_root addition (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#292]
Additional logic that wasn't in the initial ticket: https://github.com/keeleinstituut/tv-tolkevarav/issues/120

[Wiki (initial version - 3e20928)[ https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)/3e20928b627c3124a268c324173388e5f72f207d]
[Wiki (updated - ID)](https://github.com/keeleinstituut/tv-tolkevarav/wiki/4.-Rollihalduse-moodul-(Kasutajate-ja-rollide-haldus)#22-editing-a-role)
View changes with compare versions.

Main user role logic has been added (is_root=true)
BE ticket: https://github.com/keeleinstituut/tv-tolkevarav/issues/291

To-do:
- applying additional validation logic if editable role has is_root=true

**Comment by KaarelKa** [comment]
Extra note for development:

The checkboxes in is_root=true Role form will remain active, however if the user tries to click on any of them, they will get an error notification with "Peakasutaja privileege ei saa muuta" or some similar info

**Comment by IngaSokman** [comment]
@thenouan I see that currently I don't have any roles that have is_root=true. Could you please add it?

**Comment by IngaSokman** [comment]
@KaarelKa If the main user's default privileges cannot be changed, could the user add more privileges? By "by checkboxes will remain active" do you mean that the default privileges' checkboxes will be active as checked and blue or rather disabled and grey?

**Comment by thenouan** [comment]
> I see that currently I don't have any roles that have is_root=true. Could you please add it?

This is fine now. Role name was different when the migration was applied to change "main user role's" is_root field value to true, which is why the role wasn't changed to is_root. All other main user roles are fine

**Comment by KaarelKa** [comment]
1. I would say that the user can't add any privileges in this case. If I'm not mistaken, then the root user will always have all the privileges and those privileges can't be removed, so we should never have the case, where they need to add any privileges. I think BE will also block any changes to privileges on root user. However @thenouan and @PlaksoBirgit can correct me if I'm wrong.

2. "Checkboxes will remain active" - This means that we will not disable them, however if the user tries to click on them/make changes on the root user form, we will not save the values in the form, instead we should show them the error alert that the privileges can't be changed for the root user role. So they will be "active as checked and blue", but the user can't uncheck them.

**Comment by PlaksoBirgit** [comment]
1. seems correct!

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

It's OK
