### ISSUE TITLE
User data editing - is_root validation for role edit (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#296]
Initial ticket: #138 

[Wiki - old - 1a6921c](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)/1a6921ceceba9990d1c6c6fc88f5ae46c44dd270#2-editing-user-data)
[Wiki - new](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#2-editing-user-data)
Versions and changes can be compared in Wiki.

BE issue: https://github.com/keeleinstituut/tv-tolkevarav/issues/295

To-do:
- applying additional logic related to is_root=true and it's only user with that role

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.171 (Official Build) (64-bit))

It's OK
