### ISSUE TITLE
Table filtering improvements

### ISSUE THREAD

**Issue by plakitkelly** [keeleinstituut/tv-tolkevarav#411]
Related (should be done together): 
#405 
#412 

1. By selecting the filter (role, status) that show 1-2 users, the size of the table will decrease so much that choosing a new filter is not visible enough 
![image](https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/cdd37c51-fec6-4251-99f8-9c5acaf4ad73)
![image](https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/11d55916-1452-4d45-979a-d36b7240dd3e)

A possible option to fix them: 
- The table has a fixed minimum size(height) that it cannot get smaller than
- rendering the filter dropdown ontop of the table (So it will be fully visible regardless of the table)

**Comment by MariusJulius** [comment]
2. https://github.com/keeleinstituut/tv-tolkevarav/issues/437

**Comment by superspartak** [comment]
@MariusJulius It seems @KaarelKa created and merged a branch for #405 and #412.

**Comment by plakitkelly** [comment]
Tested in 27.09. It's OK
