### ISSUE TITLE
Removing text for uploading multiple csv files

### ISSUE THREAD

**Issue by plakitkelly** [keeleinstituut/tv-tolkevarav#414]
According to this text, the user should be able to add multiple files
![image](https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/ee92c6ab-e06c-4ef3-8e33-8b1cbd364de5)

I didn't find in the wiki if the user must be able to add multiple files

**Comment by MariusJulius** [comment]
It should be one file at once, need to change the wording there.

**Comment by KaarelKa** [comment]
**Note for developer** The input accepts "multiple" prop, this text should only be visible, if "multiple" is true

**Comment by MariusJulius** [comment]
Fixed.
