### ISSUE TITLE
Alphabetical ordering for sorting (BE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#431]
For example in user management we user sorting by name, Estonian letters ÕÄÖÜ are misplaced eg. ÕÖ next to O and so on.   Those letters should be as ... TUVWÕÄÖÜXWZ...

To-do:
- Fix sorting so order of letters would be correct.

**Comment by thenouan** [comment]
@kadmit I saw you added collation to serveral services. Can you put an overview here as well in what services and in what endpoints it was done?

**Comment by kadmit** [comment]
@thenouan Here is the overview of where and how collation was added:
- tv-translation-order-service
  - Institution user list endpoint inline collation.
  - Vendor list endpoint inline collation.
  - `tags.name` table column collation.
  - `vendors.company_name` table column collation.
  - `skills.name` table column collation.
- tv-authorization-service
  - `institutions.name` table column collation.
  - `institutions.short_name` table column collation.
  - `departments.name` table column collation.
  - `roles.name` table column collation.
  - `users.forename` table column collation.
  - `users.surname` table column collation.

**Comment by plakitkelly** [comment]
Tags view OK

**Comment by plakitkelly** [comment]
Institution user list NOT OK

**Comment by plakitkelly** [comment]
@MariusJulius Actually estonian letters should be: 
![Image](https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/ab857c43-ad18-4448-8b4c-5a61d8238a77)
R S Š Z Ž T

**Comment by plakitkelly** [comment]
Institution user list sorting - OK
