### ISSUE TITLE
By selecting the filter (role, status) that returns no matches, the table disappears (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#437]
By selecting the filter (role, status) that returns no matches, the table disappears.
https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/e62463fc-4210-4f55-9025-c5187feb4589

A possible option to fix them:
The table header must remain visible even though there are no matches

**Comment by plakitkelly** [comment]
Tested in 27.09. It's OK
