### ISSUE TITLE
Tag bugs (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#449]
Relates to: 
#125
#93  

To-do:
- Oskused (skill) tags are predefined, need to be removed from dropdown. Those can't be edited by the user in I phase.
- Change modal titles must reflect tag category being edited: teostaja siltide muutmine, tõlkemälu siltide muutmine. Currently every modal has text "Tellimuse siltide muutmine"

**Comment by plakitkelly** [comment]
Tested in 27.09. It's OK
