### ISSUE TITLE
Riigipilve tellimine

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#57]
Riigipilv as the main hosting / development environment

**To-do:**
- [x] Provide initial resources needed (Singleton)
- [x] Order riigipilv (Martin)

**Comment by MariusJulius** [comment]
Order made, estimation 1 week. After that we can start with setup: 
- #56

**Comment by thenouan** [comment]
Update: currently we have only one account, but order to Riigipilv has been sent to create separate accounts to every developer

**Comment by thenouan** [comment]
Got the accounts
