### ISSUE TITLE
User choosing / switching institution in translation hub

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#60]
AS AN end user 
I WANT TO be able to choose / switch account 
SO that I can manage translation services for different institutions

[User flow](https://github.com/keeleinstituut/tv-tolkevarav/wiki/1.-Sisselogimine--&--autentimine-(Kasutajate-ja-rollide-haldus)#3-switching-account)
[Login institution select view](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=936%3A91615&t=l7hqDqwxrLbY6ABM-1)
[Dashboard institition switch](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=640%3A84705&t=l7hqDqwxrLbY6ABM-1)

Prerequisite:
- #102
- User is in more than 1 institution
- #111 
- [Modal component#259](https://github.com/keeleinstituut/tv-tolkevarav/issues/259)

**To-do:**
- [ ] Display account switching option when more than 1 institution is available (FE)
- [ ] Apply user role (privileges) in the system according to the institution chosen (FE)

Acceptance criteria:
- user can select an institution when logging in 
- user can switch institutions 
- user views, permission, and privileges are changed according to the institution

**Comment by plakitkelly** [comment]
Tested with Google Chrome Version 115.0.5790.110 (Official Build) (64-bit)
(Also checked with Edge and Firefox)

It's OK
