### ISSUE TITLE
User's personal data privileges (BE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#657]
Navigate to "Minu andmed" view
[wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/B-23.-Isikuandmete-muutmise-vaade)
Users cannot edit their data without edit_user privilege. According to wiki, user doesn't need any privilege to edit their own data.

This can cause problems if all users have edit_user privilege.

FE part will be done in this task, but we need a task for BE as well. Currently BE won't allow the editing of user's own details without the edit_user privilege.

_Originally posted by @KaarelKa in https://github.com/keeleinstituut/tv-tolkevarav/issues/482#issuecomment-1855528225_

To-do:
- allow the editing of user's own details without the edit_user privilege

**Comment by MariusJulius** [comment]
@KaarelKa can I close the BE ticket and you can do the fix in #482 ?

**Comment by KaarelKa** [comment]
@MariusJulius yeah, sounds good

**Comment by MariusJulius** [comment]
Marking as closed, action needed in #482 FE ticket.
