### ISSUE TITLE
Test Tara contract

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#67]
Prerequisite:
- [x] confirm dev domain 

**To-do:**
- [x] Fill contract
- [x] Pass to Martin

**Comment by DanBondarenko** [comment]
[TARA-testkeskkonna-liitumistaotlus (1).pdf](https://github.com/keeleinstituut/tv-tolkevarav/files/10568487/TARA-testkeskkonna-liitumistaotlus.1.pdf)
