### ISSUE TITLE
Order management bugs

### ISSUE THREAD

**Issue by plakitkelly** [keeleinstituut/tv-tolkevarav#691]
1. Create new order
2. Open just created sub-order
3. Open task tab and add vendor to task

Actual result: 

- Selected vendor is not shown in Teostajad table
![image](https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/163ccc7c-7d5f-4490-aea3-27d366cfd0ce)

- In Teostajate valimine modal I can see that vendor is selected, but cannot remove this vendor, checkbox is disabled
![image](https://github.com/keeleinstituut/tv-tolkevarav/assets/130659408/718e6552-edd4-47c3-aab3-d0faf303ae4f)

- When task is splitted and all vendors are selected, Saada alamtellimus teostajatele button is still disabled

**Comment by KaarelKa** [comment]
@plakitkelly Couldn't reproduce right now, but we had 1 bug, which affected all tables. Can you test again ? 

"In Teostajate valimine modal I can see that vendor is selected, but cannot remove this vendor, checkbox is disabled" - Yeah this is intended, vendors can't be removed from that modal

**Comment by plakitkelly** [comment]
Checkbox disabled- my bad, forgot that already
Now I see selected vendors in task table. I close this ticket, none of these issues are relevant
