### ISSUE TITLE
Setting up authorization service

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#78]
[Specification](https://github.com/keeleinstituut/tv-tolkevarav/wiki/5.-Autoriseerimine,--kasutajate-lisamine-s%C3%BCsteemi-(Kasutajate-ja-rollide-haldus)#authorization)

**To-do:**
- [x] User authorization by role (privileges) and institution
- [x] datamodel

Relates to: 
- #58

**Comment by DanBondarenko** [comment]
@thenouan Two pull requests are ready for reviewing:
* https://github.com/keeleinstituut/tv-authorization/pull/1
* https://github.com/keeleinstituut/tv-authorization/pull/2
