### ISSUE TITLE
Language classficators

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#85]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/2.-Klassifikaatorid,-baasfunktsionaalsus-(Klassifikaatorite-haldus-ja-k%C3%B5ige-vajalikumaid-klassifikaatorid)#11-classifier-type-language)

**To-do:**
- Add language classificators to classifier service db

**Comment by MariusJulius** [comment]
@PlaksoBirgit who should provide the full ~50 list?

**Comment by PlaksoBirgit** [comment]
@MariusJulius Best to get the initial list from Nele and then we could confirm the list with the end users. The last time it was discussed the list might be even 100-200 items (also including 3 most common sign languages: EST, RU, International)

**Comment by MariusJulius** [comment]
@NeleKo add/update classifier values names translations.
[language-classifier.csv](https://github.com/keeleinstituut/tv-tolkevarav/files/11269315/language-classifier.csv)

**Comment by NeleKo** [comment]
@MariusJulius 
I have updated the language classifier list. I took out some very rare languages.
[language-classifier_Estonian.csv](https://github.com/keeleinstituut/tv-tolkevarav/files/11297488/language-classifier_Estonian.csv)
