### ISSUE TITLE
Create tags management view UI (FE)

### ISSUE THREAD

**Issue by MariusJulius** [keeleinstituut/tv-tolkevarav#93]
[Wiki](https://github.com/keeleinstituut/tv-tolkevarav/wiki/2.-Klassifikaatorid,-baasfunktsionaalsus-(Klassifikaatorite-haldus-ja-k%C3%B5ige-vajalikumaid-klassifikaatorid)#21-creating-tags)
[Design](https://www.figma.com/file/VqCwED3Dymn7L1gGoAOK27/EKI-t%C3%B5lkev%C3%A4rav?node-id=427%3A46968&t=0eH5ypeJoJPadoYd-1)

BE tasks #94 #95 

To-do:
- create tag management view
- enable to add new tags to categories
- showing added tags
- only users with the privilege "Siltide lissamine" (add_tags) can add tags (Confirm)

**Comment by IngaSokman** [comment]
1. Added validations to FE as well for: “Empty tag entry is not allowed” , “There should be a limit in length - e.g 50 characters” and “Only alphanumeric characters, hyphen and space are allowed, but not as the first character”.
2. When user doesn't have the privilege - inputs are disabled and buttons hidden.

**Comment by IngaSokman** [comment]
Currently waiting for Martine's input on removing tag input when adding tags.

**Comment by plakitkelly** [comment]
Tested with Google Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

It's OK
